apiVersion: apps/v1
kind: Deployment #for deployment
metadata: 
  name: registration-deployment
spec: #how many deployments
  replicas: 4
  selector:
    matchLabels:
      app: registration 
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration
        image: sanjana3082004/registration:v1   # use your Docker Hub image
        ports:
        - containerPort: 5000

